### ISSUE TITLE
Issues with 4.4.2

### ISSUE THREAD

**Issue by gnzlbg** [sabotage-linux/kernel-headers#16]
I have the following two issues with the linux kernel headers version 4.4.2 and musl 1.0.22:

* redefinitions of `struct ethhdr` when `linux/if_ether.h` is included after `netinet/if_ether.h` - reproducer:

```c
#include <netinet/if_ether.h>
#include <linux/if_ether.h>
int main() { return 0; }
```

* `fatal error: linux/module.h: No such file or directory` seems like the file is missing?

The 3.x kernel headers don't have this issue.

**Comment by rofl0r** [comment]
oh, this slipped through because i kept overwritten the headers installed into my test directory. seems module.h was still around from a previous test. should be fixed in the commit tagged as v4.4.2-1.
thanks for testing!

**Comment by gnzlbg** [comment]
thanks for the quick fix! it looks fixed, i'm going to continue migrating to the new sources and will report if there are any issues (or once I'm done, that no issues were found).

**Comment by gnzlbg** [comment]
I'm getting a redefinition of `ifmap` when including `net/if.h` and then including `linux/if.h`: 

```c
#include<net/if.h>
#include<linux/if.h>
int main() { return 0; }
```

**Comment by gnzlbg** [comment]
Also when including `linux/if.h` I'm also seeing this error:

```
include/linux/if.h:71:2: error: expected identifier before numeric constant
IFF_UP    = 1<<0,  /* sysfs */
^~~~~~
```

**Comment by rofl0r** [comment]
thanks, pushed v4.4.2-2

**Comment by gnzlbg** [comment]
Thank you! All of our tests passed. There are a couple of things that we are using that need newer kernel header versions:

*  FALLOC_FL_UNSHARE_RANGE  requires kernel headers 4.9
* MSG_COPY requires kernel headers 5.0

**Comment by gnzlbg** [comment]
We just starting using `F_SEAL_FUTURE_WRITE` from 5.1 today.. is there maybe a way I can help with this project ?
