### ISSUE TITLE
Standby problem with kernel version 5.0.16

### ISSUE THREAD

**Issue by mortim59** [sabotage-linux/kernel-headers#17]
OS: Ubuntu 18.04.2 LTS x86_64
    Kernel: 4.18.0-51-generic
    Shell: fish

I have a problem when I update it for a version 5.0.16, I have a problem of standby yet it is a stable version, why?

**Comment by rofl0r** [comment]
maybe you need some new kernel config items activated, or maybe there's a regression in the driver for the specific hardware you use. did you use the vanilla kernel config of sabotage?

**Comment by mortim59** [comment]
> maybe you need some new kernel config items activated, or maybe there's a regression in the driver for the specific hardware you use. did you use the vanilla kernel config of sabotage?

No, I don't use this

**Comment by rofl0r** [comment]
oh i see. you use ubuntu. i suppose you should ask in a ubuntu support forum instead? why do you think sabotage linux issue tracker is the right place to ask about your ubuntu problems?

**Comment by mortim59** [comment]
> oh i see. you use ubuntu. i suppose you should ask in a ubuntu support forum instead? why do you think sabotage linux issue tracker is the right place to ask about your ubuntu problems?

I thought my problem came from linux headers and not ubuntu (and I use more precisely linux mint but it's based on ubuntu)

**Comment by rofl0r** [comment]
> I thought my problem came from linux headers

very unlikely. anyway, linux mint doesn't use sabotage linux kernel headers.

**Comment by mortim59** [comment]
Okay, thanks anyway.
